language: bash
services: docker

env:
  - VERSION=7.0

before_script:
  - env | sort
  - test latest = "$VERSION" || cd "$VERSION"
  - image="marceloalmeida/php-excel-builddeb:${VERSION}"

script:
  - docker build -t "$image" .
  - docker run -it --rm -v $(pwd)/pkg:/pkg $image bash -c "cp /root/excel-*/*.deb /pkg; chmod 777 /pkg -R"
  - deb_package=$(ls $(pwd)/pkg)
  - ls -lh $(pwd)/pkg/${deb_package}

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "$(pwd)/pkg/${deb_package}"
  skip_cleanup: true
  on:
    tags: true

# vim:set et ts=2 sw=2:
